-dontwarn io.lemon.core.ui.architecture.BaseEffect
-dontwarn io.lemon.core.ui.architecture.BaseEvent
-dontwarn io.lemon.core.ui.architecture.BaseState
-dontwarn io.lemon.core.ui.architecture.BaseError
-dontwarn io.lemon.core.ui.architecture.BaseViewModel
